// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.apriltag.*;
import org.photonvision.PhotonCamera;
import org.photonvision.PhotonUtils;
import frc.robot.Constants.AprilTagConstants;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.motorcontrol.MotorController;
import edu.wpi.first.wpilibj.motorcontrol.Spark;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Vision extends SubsystemBase {
    private final PhotonCamera aprilTagCamera1 = new PhotonCamera("aprilTagCamera");
    
    
    /**
    *
    */
    public Vision() {
    
    }

    public double getTagYawDegrees(){ //x error
        return aprilTagCamera1.getLatestResult().getBestTarget().getYaw();
    }

    public double getTagYawRadians(){
        return Math.toRadians(getTagYawDegrees());       
    }


    public double getTagPitchDegrees(){ //y error
        return aprilTagCamera1.getLatestResult().getBestTarget().getPitch();
    }

    public double getTagPitchRadians(){ 
        return Math.toRadians(getTagPitchDegrees());       
    }

    
    public int getTagId(){
        return aprilTagCamera1.getLatestResult().getBestTarget().getFiducialId();
    }


    public double getRangeFromTagMeters(){
        double range = 0;
        range = PhotonUtils.calculateDistanceToTargetMeters(
            AprilTagConstants.cameraHeightMeters,
            AprilTagConstants.targetRangeMeters,
            AprilTagConstants.cameraPitchRadians,
            getTagPitchRadians()
        );
        return range;
    }



    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

